# Generated by Django 4.1.3 on 2022-11-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_module_app', '0005_auto_20211126_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='files',
            name='subject',
            field=models.CharField(choices=[('Устройство и эволюция программного обеспечения', 'Устройство и эволюция программного обеспечения'), ('Копьютерные сети', 'Копьютерные сети'), ('Человек и компьютер', 'Человек и компьютер'), ('Проектирование програмных систем', 'Проектирование програмных систем'), ('Педагогика и Психология', 'Педагогика и Психология')], max_length=50, verbose_name='Предмет'),
        ),
    ]
