# Generated by Django 4.1.3 on 2022-11-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_module_app', '0007_alter_files_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='subject',
            field=models.CharField(choices=[('Устройство и эволюция программного обеспечения', 'Устройство и эволюция программного обеспечения'), ('Управление ИТ-проектами', 'Управление ИТ-проектами'), ('Предварительная отработка данных', 'Предварительная отработка данных'), ('Программирование на JavaScript', 'Программирование на JavaScript'), ('Дополнительно', 'Дополнительно')], max_length=50, verbose_name='Предмет'),
        ),
    ]
